### ISSUE TITLE
Error when using in multisite

### ISSUE THREAD

**Issue by Zephirus2** [GM-Alex/user-access-manager#383]
I created a new site and I get this error the logs:

```
[08-Sep-2023 11:03:42 UTC] PHP Fatal error:  Uncaught TypeError: version_compare() expects parameter 1 to be string, bool given in /home//www/wp-content/plugins/user-access-manager/src/Setup/Database/DatabaseHandler.php:340
Stack trace:
#0 /home//www/wp-content/plugins/user-access-manager/src/Setup/Database/DatabaseHandler.php(340): version_compare(false, '1.6.2', '<')
#1 /home//www/wp-content/plugins/user-access-manager/src/Controller/Backend/BackendController.php(85): UserAccessManager\Setup\Database\DatabaseHandler->isDatabaseUpdateNecessary()
#2 /home//www/wp-includes/class-wp-hook.php(310): UserAccessManager\Controller\Backend\BackendController->showAdminNotice('')
#3 /home//www/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(false, Array)
#4 /home/s/www/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /home//www/wp-admin/admin-header.php(303): do_action('admin_notices')
#6 /home//www/wp-admin/tools.php(60): require_once('/home/vimapms/w...')
#7 {main}
  thrown in /home/vimapms/www/wp-content/plugins/user-access-manager/src/Setup/Database/DatabaseHandler.php on line 340
```

aswell as errors of this type:

`WordPress database error Table 'name.mod38_3_uam_accessgroups' doesn't exist for query SELECT ID FROM mod38_3_uam_accessgroups made by require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), do_action('plug`i$`

and 

 ```
WordPress database error Table 'name.mod38_3_uam_accessgroup_to_object' doesn't exist for query SELECT object_id AS id, object_type AS objectType, from_date AS fromDate, to_date AS toDate
                FROM mod38_3_uam_accessgroup_to_object
                WHERE group_id = '0'
                  AND group_type = 'user'
                  AND object_id != ''
                  AND (general_object_type = '_user_' OR object_type = '_user_') AND (from_date IS NULL OR from_date <= '2023-09-08 11:03:43') AND (to_date IS NULL OR to_date >= '2023-09-08 11:03:43') made by require_once('wp-load.php'), require_once('wp-config.php'), require_$
```

**Comment by GM-Alex** [comment]
The version error is fixed with 2.2.23

**Comment by GM-Alex** [comment]
I close this issue because it's quite old. If it's still relevant, please feel free to reopen it.
